package com.bls.rendezvous;import android.app.Activity;import android.os.Bundle;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.widget.*;import android.content.Intent;import android.net.Uri;import android.util.TypedValue;import android.content.SharedPreferences;
public class MainActivity extends Activity{int L=0;protected void onCreate(Bundle b){super.onCreate(b);L=getSharedPreferences("bls",0).getInt("lang",0);home();}
void home(){int c1=Color.parseColor("#0F0C29"),c2=Color.parseColor("#302B63");int[] cl={c1,c2,Color.parseColor("#24243E")};GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,cl);ScrollView sv=new ScrollView(this);LinearLayout m=new LinearLayout(this);m.setOrientation(1);m.setPadding(dp(20),dp(35),dp(20),dp(20));m.setBackground(bg);
LinearLayout t=new LinearLayout(this);t.setOrientation(0);TextView lo=new TextView(this);lo.setText("BLS");lo.setTextSize(20);lo.setTextColor(-1);lo.setTypeface(null,1);LinearLayout.LayoutParams lp1=new LinearLayout.LayoutParams(0,-2,1);lo.setLayoutParams(lp1);t.addView(lo);
TextView se=new TextView(this);se.setText("⚙ Settings");se.setTextColor(Color.parseColor("#9AA0B6"));se.setOnClickListener(v->settings());t.addView(se);m.addView(t);
String a=L==2?"خدمات التأشيرة":L==1?"Services Visa":"Visa Services",b=L==2?"احجز موعدك":L==1?"Reservez RDV":"Book appointment";TextView t1=new TextView(this);t1.setText("\n"+a);t1.setTextSize(30);t1.setTextColor(-1);t1.setTypeface(null,1);m.addView(t1);TextView t2=new TextView(this);t2.setText(b+"\n");t2.setTextColor(Color.parseColor("#9AA0B6"));t2.setPadding(0,dp(8),0,dp(20));m.addView(t2);
m.addView(card(L==2?"جواز السفر":L==1?"Passeport":"Passport","New Renew Track",0));m.addView(card(L==2?"مراكز التأشيرة":"Centres Visa","Algiers Oran",1));m.addView(card(L==2?"مواعيدي":"Mes RDV","View Manage",2));m.addView(card("Support","BLS",3));
TextView btn=new TextView(this);btn.setText(L==2?"ابدأ":L==1?"Commencer":"Get Started");btn.setTextSize(18);btn.setTextColor(c1);btn.setGravity(17);btn.setTypeface(null,1);GradientDrawable g=new GradientDrawable();g.setCornerRadius(dp(30));g.setColor(-1);btn.setBackground(g);LinearLayout.LayoutParams pr=new LinearLayout.LayoutParams(-1,dp(56));pr.topMargin=dp(25);btn.setLayoutParams(pr);btn.setPadding(0,dp(14),0,dp(14));btn.setOnClickListener(v->open("https://algeria.blsspainvisa.com/"));m.addView(btn);sv.addView(m);setContentView(sv);}
LinearLayout card(String a,String b,int t){LinearLayout ca=new LinearLayout(this);ca.setOrientation(0);ca.setGravity(16);ca.setPadding(dp(18),dp(16),dp(18),dp(16));GradientDrawable g=new GradientDrawable();g.setCornerRadius(dp(18));g.setColor(Color.parseColor("#22FFFFFF"));g.setStroke(1,Color.parseColor("#33FFFFFF"));ca.setBackground(g);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(12);ca.setLayoutParams(lp);LinearLayout tx=new LinearLayout(this);tx.setOrientation(1);TextView tt=new TextView(this);tt.setText(a);tt.setTextColor(-1);tt.setTextSize(16);tt.setTypeface(null,1);tx.addView(tt);TextView dd=new TextView(this);dd.setText(b);dd.setTextColor(Color.parseColor("#9AA0B6"));dd.setTextSize(11);tx.addView(dd);ca.addView(tx);if(t==0)ca.setOnClickListener(v->passport());if(t==1)ca.setOnClickListener(v->centers());if(t==2)ca.setOnClickListener(v->appoint());if(t==3)ca.setOnClickListener(v->open("https://algeria.blsspainvisa.com/"));return ca;}
void passport(){LinearLayout m=base();m.addView(title("Passport"));LinearLayout c1=nc("New Passport","Apply");c1.setOnClickListener(v->open("https://algeria.blsspainvisa.com/book_appointment.php"));m.addView(c1);LinearLayout c2=nc("Renew Passport","Renew");c2.setOnClickListener(v->open("https://algeria.blsspainvisa.com/"));m.addView(c2);LinearLayout c3=nc("Track Status","Track");c3.setOnClickListener(v->track());m.addView(c3);LinearLayout c4=nc("Requirements","Docs");c4.setOnClickListener(v->open("https://algeria.blsspainvisa.com/"));m.addView(c4);show(m);}
void track(){LinearLayout m=base();m.addView(title("Track Status"));EditText e=input("BLS123456");m.addView(e);TextView b1=bd("Track on BLS");b1.setOnClickListener(v->open("https://algeria.blsspainvisa.com/track_application.php"));m.addView(b1);TextView b2=bd("Check Here");m.addView(b2);TextView r=new TextView(this);r.setPadding(0,dp(20),0,0);m.addView(r);b2.setOnClickListener(v->{String tr=e.getText().toString();if(tr.isEmpty()){r.setText("Enter number");return;}r.setText("Status "+tr+":\n✓ Received\n✓ Processing\n○ Ready");});show(m);}
void centers(){LinearLayout m=base();m.addView(title("BLS Centers"));m.addView(cc("BLS Algiers","El Biar"));m.addView(cc("BLS Oran","Bir El Djir"));m.addView(cc("BLS Constantine","Zouaghi"));TextView mp=bd("Open in Maps");mp.setOnClickListener(v->open("https://www.google.com/maps/search/BLS+Spain+Algeria"));m.addView(mp);TextView mp2=bd("BLS Website");mp2.setOnClickListener(v->open("https://algeria.blsspainvisa.com/"));m.addView(mp2);show(m);}
void appoint(){LinearLayout m=base();m.addView(title("My Appointments"));LinearLayout c
